name: GitHub CI
on: [push]
jobs:
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: yarn run semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: Octadesk Semantic Release
          GIT_AUTHOR_EMAIL: tech@octadesk.com
          GIT_COMMITTER_NAME: Octadesk Semantic Release
          GIT_COMMITTER_EMAIL: tech@octadesk.com
