name: GitHub CI
on: [push]
env:
  NODE_VERSION: 16
jobs:
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@octadesk-tech'
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Publish
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: Octadesk Semantic Release
          GIT_AUTHOR_EMAIL: tech@octadesk.com
          GIT_COMMITTER_NAME: Octadesk Semantic Release
          GIT_COMMITTER_EMAIL: tech@octadesk.com
